### ISSUE TITLE
Default shared/anonymous configuration without using own Google account

### ISSUE THREAD

**Issue by emanuelb** [rehmatworks/gplaydl#15]
Currently using this tool require to supply email&password for google account, this issue is about avoiding it by supporting Anonymous mode that use shared account, see for example other projects that implement this:
gplaycli: https://github.com/matlink/gplaycli

> By default, gplaycli fetches a token from a token dispenser server located at https://matlink.fr/token/ to login in Google Play.

AuroraStore app: https://gitlab.com/AuroraOSS/AuroraStore

> Anonymous accounts — You can log in and download with anonymous accounts so you don't have to use your own account

YalpStore app: https://github.com/yeriomin/YalpStore

> By default Yalp Store connects to Google services using a built-in account, so you do not have to own a Google account to use it

**Comment by rehmatworks** [comment]
Hello @emanuelb At the moment, I am somehow busy and I don't have time in order to maintain a token dispenser server. If you can send in a pull request by implementing an existing token dispenser server, that'd be awesome. Otherwise I'll consider this feature in the upcoming days.
