### ISSUE TITLE
Youtube video broken from video

### ISSUE THREAD

**Issue by 1-alex98** [rehmatworks/gplaydl#16]
Says the account was deleted

**Comment by rehmatworks** [comment]
@1-alex98 Thank you for bringing this into my attention. I see that the account has been deleted by Google, maybe it's because `gplaydl` gets the access to APKs without their permission.

**Comment by NTT1906** [comment]
> @1-alex98 Thank you for bringing this into my attention. I see that the account has been deleted by Google, maybe it's because `gplaydl` gets the access to APKs without their permission. I have appealed against this.

wait, so this broke now?

**Comment by rehmatworks** [comment]
@NTT1906 No. The code hasn't broken. The video violated their TOS and was removed from YouTube.
