### ISSUE TITLE
How to create device profile from a real device

### ISSUE THREAD

**Issue by Bnaya** [rehmatworks/gplaydl#2]
First, thank you for your amazing project!

I have a given device, And i want to create device.properties entry for it.
What is the most simple way to do so?
Is there any script that can do that?
Thanks!

**Comment by rehmatworks** [comment]
Unluckily, I don't know of any software that could be used use to build the properties files on the fly. You can check https://github.com/NoMore201/googleplay-api/blob/master/gpapi/device.properties for examples and can try to build your own properties section.
