### ISSUE TITLE
Login failed. Ensure that correct credentials are provided.

### ISSUE THREAD

**Issue by PacoH** [rehmatworks/gplaydl#3]
This used to work. Now it doesn't, even with valid credentials.

   $ gplaydl -id com.whatsapp
Login failed. Ensure that correct credentials are provided.

**Comment by mysticaltech** [comment]
Same here! What could be happening?

**Comment by worldofprasanna** [comment]
Yes. For me too !!

**Comment by arbitraryrw** [comment]
Looks like the response from the `GooglePlayAPI.login` has changed for one reason or another. This means the token key referenced for login will be None. I imagine this is why your logins are failing.

The snippet below is what the current dictionary response looks like from `GooglePlayAPI.login`:

```
{'authSubToken': None, 
'gsfId': None, 
'device_config_token': None, 
'deviceCheckinConsistencyToken': None, 
'dfeCookie': None, 
'proxies_config': None, 
'deviceBuilder'None
}
```

**Comment by PacoH** [comment]
> the token key referenced for login will be None. I imagine this is why your logins are failing.

So what can we, the users, do about it?

**Comment by arbitraryrw** [comment]
Just looked through the source a bit more thoroughly, it is correctly referencing `authSubToken`. I'm building something on top of the [googleplay-api](https://github.com/NoMore201/googleplay-api) which this tool is built on, if I find any issues I'll make sure to update.

**Comment by PacoH** [comment]
>  I'm building something on top of the googleplay-api which this tool is built on, if I find any issues I'll make sure to update.

Oh. that would be great. Thanks a lot.

**Comment by rehmatworks** [comment]
Are you using app passwords? Regular passwords will trigger a security challenge at Google's end. I ran a test and all looks fine for me. It works pretty well. Ensure that you are using app passwords. I'll do more testing and I'll release an upgrade if something needs a rewrite.

**Comment by PacoH** [comment]
I even uninstalled and reinstalled the app

	Successfully uninstalled gplaydl-1.0.3
	Successfully installed gplaydl-1.0.3

and added credentials to config file

	gplaydl --configure -e email@gmail.com -p passwordOrAppPassword
	Configuration file created successfully! Try downloading an APK file now.

Still getting:

Login failed. Ensure that correct credentials are provided.

I am even already logged in to my account in Chrome.

**Comment by rehmatworks** [comment]
@PacoH I've released a major upgrade. Even the old version was working fine for me (on Ubuntu servers and on my Macbook Pro), but that was using an older version of gpapi. Now I've published a custom version of gpapi and I'm using it for `gplaydl`.

To upgrade to the latest version, execute this in your terminal:
```bash
pip3 install --upgrade --force-reinstall gplaydl
```

In terms of app passwords, they aren't like the API keys. Would you kindly do a Google search? You should be able to set up an application-specific password within 5 minutes.  If you can't find help from Google, follow these instructions:

1. Go to your [Google account settings](https://myaccount.google.com/)
2. Go to "Security Settings" & and then enable 2-factor auth on your account
3. Once 2-factor auth is enabled, [create an app password here](https://myaccount.google.com/apppasswords)

And then use that app password in place of your regular account password. Once you have your login info, write the following command in terminal:

```bash
gplaydl configure
```
And hit enter. You will be asked for your Google email and password. Provide your Google email and app password. If all goes well, your auth config will be configured.

Now try downloading an app:
```bash
gplaydl download --packageId com.twitter
```

And please check the readme in the main repo for complete documentation. To improve the code and overall functionality of the package, I have rewritten a major part of it and commands are changed too. I hope you will love the new version.

I hope this explanation addresses the issues for all of you.

**Comment by PacoH** [comment]
OK. Thanks. I upgraded and now it doesn't even run.

	gplaydl
	Traceback (most recent call last):
	  File "/usr/local/bin/gplaydl", line 7, in <module>
		from gplaydl.gplaydl import main
	  File "/usr/local/lib/python3.6/site-packages/gplaydl/gplaydl.py", line 9, in <module>
		import validators
	ModuleNotFoundError: No module named 'validators'

**Comment by rehmatworks** [comment]
`pip3 install validators `

BTW this module should get installed itself. I don't know what went wrong. Please run `pip3 install validators` and that should fix your issue.

**Comment by rehmatworks** [comment]
Strangely, the requirements were removed from `setup.py` file. Thank you for reporting this issue. I've added the requirements in `setup.py` file as well as have included a `requirements.txt` file too. Now installing the package from PyPi forcing a reinstall i.e. `pip3 install --upgrade --force-reinstall gplaydl` should work.

**Comment by PacoH** [comment]
Thanks! `pip3 install validators` worked with existing and uninstalling/reinstalling worked as well. I see syntax has changed and creating config file is easier. I only added gmail and password, no app password. This is great. Good support.

**Comment by rehmatworks** [comment]
That's great. I'm closing this issue for now considering that the issue should be addressed for all users by the latest upgrade.

**Comment by nazarwaheed** [comment]
> That's great. I'm closing this issue for now considering that the issue should be addressed for all users by the latest upgrade.

AoA Rehmat

I am trying to use this api but unfortunately, the 'server says: BadAuthentication' error keeps coming up - I have generated app password and using it but still does not work - any help will be appreciated - I need to Download APKs from Google Play directly. Thanks
