### ISSUE TITLE
Is Still working this Repo?

### ISSUE THREAD

**Issue by idotnetdev** [rehmatworks/gplaydl#37]
Hi,
Is still working this Repo?
I've got Bad Authentication.

How can I debug this module in python?

**Comment by babang1da** [comment]
I have same - 'server says: BadAuthentication

**Comment by ahm750** [comment]
Can anyone recommend another package?

**Comment by i1v** [comment]
http://2a.pages.dev/googleplay

**Comment by edc1934** [comment]
Same issue. Guessing this repo is dead

**Comment by idotnetdev** [comment]
Yes this project is dead. But I fix problems, bugs and create a new project for that.
I will sell it at your suggested price.

If anyone wants to see the preview of the project and buy it, they can contact my email.
idotnetdev [at] gmail.com

**Comment by 4cq2** [comment]
Dont listen to @idotnetdev scammer. Here is some free code:

https://github.com/4cq2/googleplay

support is paid, but the code is free. have fun.
