### ISSUE TITLE
Download failed. gplaydl cannot download some apps that are paid or incompatible.

### ISSUE THREAD

**Issue by FreelancePentester** [rehmatworks/gplaydl#4]
I tried to download, but I get "Download failed. gplaydl cannot download some apps that are paid or incompatible." error. 
Any solution?
Thanks,

**Comment by rehmatworks** [comment]
Can you please mention the package ID of the app that you tried to download?

**Comment by kronicd** [comment]
I can confirm the issue above, it seems to occur with all packages. I tested it with com.twitter.android for example.
```
gplaydl download --packageId com.twitter.android
Login failed. Please re-configure your auth.
Google Email: XXX@XXX
Google Password:
Configuration file created successfully! Try downloading an app now.
Attempting to download com.twitter.android
Download failed. gplaydl cannot download some apps that are paid or incompatible.
```

It should be noted that the authentication request occurs every tgat gplaydl is executed.

**Comment by mrklintscher** [comment]
Yes i can confirm it too. Is there an update?

**Comment by rehmatworks** [comment]
As a temporary fix, please delete the `.gplaydl` folder in your home directory and try downloading an app again.

```bash
rm -r ~/.gplaydl
```

I'll push a fix but you can try this solution to see if it fixes your issue for now.

**Comment by mrklintscher** [comment]
> 
> 
> As a temporary fix, please delete the `.gplaydl` folder in your home directory and try downloading an app again.
> 
> ```shell
> rm -r ~/.gplaydl
> ```
> 
> I'll push a fix but you can try this solution to see if it fixes your issue for now.

Dosent fix it :-(

**Comment by kimberlythegeek** [comment]
Any update on this? I was able to successfully download google chrome using this tool, back in August. Currently trying to download the latest version using this command:

```
gplaydl download --packageId com.android.chrome --device walleye
```

and encountering the above error.

- After running `gplaydl configure`, I am still getting this message whenever I attempt to download: `Login failed. Please re-configure your auth.`
- I am using an app password, have deleted + recreated this with the same result
- have updated gplaydl, as well as uninstalling and re-installing from both pip and github source, neither of which fixed the problem

**Comment by NTT1906** [comment]
i'm having some problem with this
`Download failed: "Can't install. Please try again later." `

**Comment by NTT1906** [comment]
okay i know how to fix this
to download paid application, you need to use the delivery function not download ^^"

**Comment by NTT1906** [comment]
![Screenshot_20210527_222105](https://user-images.githubusercontent.com/54394881/119852983-fc305880-bf39-11eb-9794-bad67b58c8b8.jpg)


> okay i know how to fix this
> to download paid application, you need to use the delivery function not download ^^"

it's worked

**Comment by rehmatworks** [comment]
@NTT1906 Can you please send in a pull request with your changes if it works for paid apps?
