### ISSUE TITLE
server says: BadAuthentication

### ISSUE THREAD

**Issue by jauharvp** [rehmatworks/gplaydl#7]
Even after providing a valid email and password, and Enabled the "less secure app use".

**Comment by NTT1906** [comment]
Hello? I just want to ask when will this be fixed?
I'm stuck :<

**Comment by rehmatworks** [comment]
A specific version of cryptography is supported and the latest versions are raising this error. Please use requirements from the latest requirements.txt file. Downloading the latest requirements.txt file and then `pip install -r requirements.txt` file should do the trick.

**Comment by NTT1906** [comment]
it didn't work

**Comment by NTT1906** [comment]
can you help me :c 😣

**Comment by rehmatworks** [comment]
Hey @NTT1906 

I have installed these requirements in a virtual environment and it works well for me. Can you please save these requirements as `requirements.txt` file and install the packages?

```
asgiref==3.2.7
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
click==7.1.1
cryptography==2.9
decorator==4.4.2
gpapi==0.4.4
idna==2.9
itsdangerous==1.1.0
MarkupSafe==1.1.1
protobuf==3.14.0
pycparser==2.20
pytz==2019.3
requests==2.23.0
six==1.14.0
sqlparse==0.3.1
urllib3==1.25.8
validators==0.14.3
Werkzeug==1.0.1
```

Installing the requirements (`pip install -r requirements.txt`) should help. Let me know if this helps you. Remember to install these packages in the same environment where you have installed `gplaydl`

**Comment by rehmatworks** [comment]
I have pushed some major upgrades. All issues should have been fixed now. Please just install the latest version:

```bash
pip3 install gplaydl==1.3.5
```

The latest version addresses all reported issues. If you are still facing this issue, please reply back. Or close this issue if your issue is resolved.

**Comment by DannyHsuCC** [comment]
It still cannot working correct even update to 1.3.5. (Already purge old env. still cannot working.)

**Comment by vinsebastian** [comment]
Still facing issue with 'server says: BadAuthentication'

**Comment by rehmatworks** [comment]
I hope the issue has been resolved until now as I have pushed some fixes lately. If not, please reopen this issue.
